services:
  - type: web
    name: telegram-auto-join-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:10000 --timeout 120
    envVars:
      - key: BOT_TOKEN
        value: "8284891252:AAG8fWcoprmDxe220rz17gD8tg7l32CwD0A"